# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Maksim Slesarenko
title: Web developer
email: masxlesfrom@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: TheVeksel
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | 
  Hi, I am Maksim Slesarenko, a second-year student of Information and Communication Technology (<mark>Web Programming</mark>) at Gradia University. I am looking for an opportunity to develop my skills and gain practical experience in <mark>web development</mark>.

  I am most skilled in: <mark>React</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Re-creation of the Yle.fi website
        link: https://github.com/TheVeksel/OmaPr
        additional_links:
          - title: sproogen/modern-resume-theme
            icon: fab fa-github
            url: https://github.com/TheVeksel/OmaPr
            quote: >
              This pet project was created as a way to deepen my understanding of React and my favorite aspect of web development — the integration of frontend and backend, specifically the handling and display of server-side data.
        description: |
  An excellent project made with React and TypeScript. It displays news fetched from a Firebase server. 
  Live demo: <a href="https://oma-pr.vercel.app/" target="_blank">https://oma-pr.vercel.app/</a>



  - title: Experience
    layout: list
    content:
      - layout: left
        title: Finnish Red Cross, Western Finland District
        sub_title: Instructor
        caption: April 2023
        description: |
          I helped refugees by translating documents and explaining where and how to get them. I also worked as a telephone operator. In this role, I learned to improve my communication skills and solve various problems effectively.

      - layout: left
        title: Jyväskylä Game
        sub_title: Mosaiikki Oy
        caption: Internship Project
        description: |
          Developed an educational game for children to learn about Jyväskylä. Includes multilingual support for expanding vocabulary in foreign languages.
          [Live demo](https://jyvaskyla-game.vercel.app/)
          Repository: [GitHub](https://github.com/TheVeksel/JyvaskylaGame)

      - layout: left
        title: Sokolye Hunting Company Website
        sub_title: Freelance Project
        caption: Independent Work
        description: |
          Created a website for a hunting company using HTML, CSS, and JavaScript. Hosted on a free platform to meet client requirements.
          [Live demo](https://oxota-sokolie.vercel.app/)
          Repository: [GitHub](https://github.com/TheVeksel/Oxota.Sokolie)

  - title: Education
    layout: list
    content:
      - layout: left
        title: Gradia Vocational School
        caption: 2023-present
        sub_title: Information and Communication Technology, Web Programming
        description: |
          104/180 osp.
          During my studies I bypassed the college curriculum and already acquired the following skills: HTML, CSS (SCSS), JS, TS, React, React-router-dom, Git, Vite, Webpack, Axios, Python, WP, Firebase, Redux toolkit.

  - title: A Little More About Me
    layout: text
    content: | 
      Along with my interests in development, I have other interests and hobbies:
      - Gaming
      - Fishing
      - Gym


# Footer
footer_show_references: false
# references_title: References on request

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
