# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Maksim Slesarenko
title: Web developer
email: masxlesfrom@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: TheVeksel
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | 
  Hi, I am Maksim Slesarenko, a second-year student of Information and Communication Technology (<mark>Web Programming</mark>) at Gradia University. I am looking for an opportunity to develop my skills and gain practical experience in <mark>web development</mark>.

  I am most skilled in: <mark>React</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Re-creation of the Yle.fi website
        link: https://github.com/TheVeksel/OmaPr
        additional_links:
          - title: sproogen/modern-resume-theme
            icon: fab fa-github
            url: https://github.com/TheVeksel/OmaPr
            quote: >
          This pet project was created as a way to deepen my understanding of React and my favorite aspect of web development — the integration of frontend and backend, specifically the handling and display of server-side data.
        description: |
          An excellent project made with <mark>React</mark> and <mark>TypeScript</mark>. It displays news fetched from a <mark>Firebase</mark> server. Live demo: <mark>https://oma-pr.vercel.app/</mark>

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Finnish Red Cross, Western Finland District
        sub_title: <mark>Instructor</mark>
        caption: April 2023
        description: |
          I helped refugees by <mark>translating documents</mark> and explaining where and how to get them. I also worked as a <mark>telephone operator</mark>. In this role, I learned to improve my <mark>communication skills</mark> and solve various problems effectively.

      - layout: left
        title: Jyväskylä Game
        sub_title: Mosaiikki Oy
        caption: <mark>Internship Project</mark>
        description: |
          Developed an educational game for children to learn about <mark>Jyväskylä</mark>. Includes <mark>multilingual support</mark> for expanding vocabulary in foreign languages. Live demo: <mark>https://jyvaskyla-game.vercel.app/</mark>  
          Repository: [<mark>GitHub</mark>](https://github.com/TheVeksel/JyvaskylaGame)

      - layout: left
        title: Sokolye Hunting Company Website
        sub_title: <mark>Freelance Project</mark>
        caption: Independent Work
        description: |
          Created a website for a <mark>hunting company</mark> using <mark>HTML</mark>, <mark>CSS</mark>, and <mark>JavaScript</mark>. Hosted on a <mark>free platform</mark> to meet client requirements. Live demo: <mark>https://oxota-sokolie.vercel.app/</mark>
          Repository: [<mark>GitHub</mark>](https://github.com/TheVeksel/SokolyeHunting)

  - title: Education
    layout: list
    content:
      - layout: left
        title: Gradia Vocational School
        caption: 2023-present
        sub_title: Information and Communication Technology, <mark>Web Programming</mark>
        description: |
          104/180 osp.
          During my studies I bypassed the college curriculum and already acquired the following skills: <mark>HTML</mark>, <mark>CSS (SCSS)</mark>, <mark>JS</mark>, <mark>TS</mark>, <mark>React</mark>, <mark>React-router-dom</mark>, <mark>Git</mark>, <mark>Vite</mark>, <mark>Webpack</mark>, <mark>Axios</mark>, <mark>Python</mark>, <mark>WP</mark>, <mark>Firebase</mark>, <mark>Redux toolkit</mark>.

  - title: A Little More About Me
    layout: text
    content: | 
      Along with my interests in <mark>development</mark>, I have other interests and hobbies:
      - <mark>Gaming</mark>
      - <mark>Fishing</mark>
      - <mark>Gym</mark>

# Footer
footer_show_references: false
# references_title: References on request

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
